gevulotnetwork/gevulot-rs

Cargo.lock, Cargo.toml, src/lib.rs, src/runtime_config.rs
This PR adds Gevulot runtime config (aka Mia runtime config) to this crate.
After these changes:
- EVE can use `gevulot_rs::runtime_config::RuntimeConfig` (tested locally)
- MIA can use `gevulot_rs` as a dependency (tested locally, `mia` binary size will be 2.6M)
- Any hand-made VM can use this module to implement runtime configuration
TODOs for the future:
- Enforce `version` field to be first in runtime configuration. In case of version mismatch, deserializer shouldn't go further.
=> Add runtime configuration module

src/base_client.rs
The original code here updated account sequence every time a transaction was successfully broadcasted, but despite of successful broadcast, the transaction could still fail, which would lead to situation where on-chain account sequence stays unchanged, but local book keeping gets one step ahead, basically leading to situation where the client instance is permanently unable to transmit any further transactions, unless some external event triggered on-chain account sequence change.
This change moves the local book keeping update to point where we know that the transaction successfully executed.
=> Update account sequence only after successful tx

proto/gevulot/gevulot/task.proto, proto/gevulot/gevulot/workflow.proto
This uses the metadata struct for representing metadata in the workflows, the same as in all the other entities
=> fix workflow protos, technically breaking!

Cargo.lock, Cargo.toml, src/runtime_config.rs
This PR adds `DebugExit` definition to runtime configuration. `DebugExit` describes how VM will report main application status to the outside world depending on architecture.
In future this may potentially be expanded to e.g. `result-file` meta-architecture, which will utilize file-based approach to report status.
R.n. only `x86` implemented, which uses `isa-debug-exit` QEMU device:
```shell
qemu-system-x86_64 -device isa-debug-exit,iobase=0xf4,iosize=0x04 ...
```
Although the options for port&size are available, there is no need to use anything except `DebugExit::default_x86()` for now.
Also this PR brings semantic versioning to runtime configuration. This will allow  for example to use this crate with `1.1` version of runtime config with config files of version `1`.
Version strings are …
=> runtime-config: add debug exit definition

proto/gevulot/gevulot/pin.proto, proto/gevulot/gevulot/tx.proto, src/builders.rs, src/events.rs
This prepares the pin protobufs so that we can make the CID optional. It adds the ID field, and also adds a "success" field to the PinAck type that will allow signaling that sara failed to pin a specific file
=> upgrade the pin protobufs, so that CID is optional

src/models.rs
When feeding a Pin spec into gvltctl, it currently blows up when no CID is defined. But since we now actually support adding Pins without CID if it has fallback urls, this needs to be changed.
=> allow empty cid in pin model

Cargo.lock, Cargo.toml
Publish with pre-release version `0.1.3-pre` just in case something goes wrong. So we won't need to bump the version from `0.1.3`, which is aligned with platform now.
After successful publish we can re-publish release version `0.1.3`.
=> Make version pre-prelease

.gitignore, Cargo.lock, Cargo.toml, README.md, build.rs, scripts/prepare_publish.sh
- Before running `cargo publish`, you should run `./scripts/prepare_publish.sh`.
- When building on `docs.rs` server, `buf` won't be used. Exported files will be compiled directly with `tonic` instead.
=> docs.rs-specific build

.github/workflows/publish.yaml
This workflow publishes to crates.io every time a tag like `v1.2.3` is pushed.
I'm not sure should we automatically publish pre-release versions like `v1.2.3-pre`, so I didn't added them for now.
For this to work we need to set `secrets.CARGO_REGISTRY_TOKEN` first.
=> Add GitHub workflow for publishing to crates.io

.github/workflows/publish.yaml
- Added manual trigger for publishing workflow. It should be run only for tags with semver naming like `v1.2.3` or `v1.2.3-pre.4` (although the check will probably fail for others anyway)
- Added check for `Cargo.toml` version and tag name to be aligned
=> Manual publishing pipeline

src/models.rs
This exposes success and error fields in the PinAck model (so we can see it in gvltctl)
=> fix pin ack model by including success and error fields

Cargo.lock, Cargo.toml
Looks like we are ready to release stable version `0.1.3` for crates.io
=> Bump `gevulot-rs` version to 0.1.3

src/base_client.rs, src/error.rs
We have handling for tx failures, after tx is broadcasted with **sync mode**:
https://github.com/gevulotnetwork/gevulot-rs/blob/ad1190dd0320a30988a4777a802526b9353b4cfd/src/base_client.rs#L332-L339
Sync mode means that basic checks are done (structure, signatures, fees), and tx is added to the mempool. However, execution still can fail **later**.
Currently we fetch the tx response and blindly start parsing its message - even if tx code is non-zero - which results in `Error: Unknown("no response message")`.
---
This PR improves handling with a dedicated Tx error: hash, code and log included.
For example, instead of "no response message" (like in https://github.com/gevulotnetwork/gvltctl/issues/44), now you will get:
```
Error: Tx("A3469D4B4A2D046B41752FA8DFA7FA2787881126E3CF1C10AFE6CB3351EA …
```
=> Tx error handling

build.rs
I had hard time using `gevulot-rs` as dependency, as every change required 5 seconds for intellisense to pick up. This was caused by upstream bug in tonic builder - see https://github.com/Valensas/tonic-buf-build/issues/7.
This PR workarounds it, by disabling all `rerun-if-changed` emits from tonic builder, and emittitng the valid one manually (hardcoded `proto` path).
=> Fix unnecessary build reruns caused by tonic bug

src/worker_client.rs
Pagination support for listing workers: fetching pages of 100 records in a loop.
Fixes #44.
=> Use pagination to list all workers

Cargo.lock, Cargo.toml
- Bump `gevulot-rs` crate version.
=> Prepare release 0.1.4

Cargo.lock, Cargo.toml
We've made some API changes and pushed `0.1.4` release, which breaks compatibility.
Right now if you depend on `gevulot-rs 0.1`, you can get get compilation error.
We have to release 0.2 version now and yank 0.1.4.
=> Bump version to 0.2

.github/workflows/publish.yaml
This tool will review the API against the latest version already released on crates.io and try to check if there is a SemVer violation (whether crate version changed properly or not).
This tool **has quite a few false negatives** and may not catch all the violations. E.g. adding new item (function, structure) to a public API doesn't trigger minor update.
You should still watch out for SemVer manually. If this step at CI is green **it doesn't mean that everything is fine**.
However I think that it's still better to have it here that not to have it: it may catch at least something and warn you on time.
=> Add SemVer violation check to publishing CI workflow

src/base_client.rs, src/gevulot_client.rs, src/gov_client.rs
This allows to set chain ID and token denomination for a client:
```rust
let client = GevulotClientBuilder::new()
.chain_id("my_chain")
.denom("my_token")
.build()
.await?;
```
Default values are:
```rust
const DEFAULT_CHAIN_ID: &str = "gevulot";
const DEFAULT_TOKEN_DENOM: &str = "ucredit";
```
=> Customize chain ID and token denomination in GevulotClient

src/models/mod.rs, src/models/pin.rs, src/models/serialization_helpers.rs, src/models/task.rs, src/models/worker.rs
- `ByteUnit`/`CoreUnit`/`TimeUnit` now use `u64` instead of `i64`. It makes no sense to store them as signed, especially because parsing negative units always results in error.
- Serialization helpers are now exposed in public API. This is needed because these types are public fields in different models, which are in public API.
- ~~Re-enabled linting and testing in CI. A bunch of tests were fixed. Old e2e tests were ignored. Clippy warnings fixed.~~
_UPD. moved to separate PR_
Doing all this revealed a number of questions. They are not resolved in this PR, however I will list them here for further discussions.
- Exposing units as public enums makes all of their variants public, which allows to create invalid `{Byte,Core,Time}Unit::String` variants. Probably private implementation pattern …
=> Refine API

src/lib.rs
Public method `BaseClient::set_signer` has argument of type `gevulot_rs::signer::GevulotSigner`, but `gevulot_rs::signer` was a private module.
=> Make signer module public

src/gevulot_client.rs
The question is: do we actually need this? Or user should just use `BaseClient` in this case.
=> Implement converting base client into gevulot client

.github/workflows/ci.yaml, src/base_client.rs, src/lib.rs, src/models/metadata.rs, src/models/pin.rs, src/models/serialization_helpers.rs, src/models/task.rs, src/models/worker.rs, src/models/workflow.rs, src/runtime_config.rs
This PR fixes a bunch of test cases (including doc tests) and clippy warnings. This allows us to run tests and lints in CI.
Requires #51 to be merged first, because test cases are fixed according to those changes.
=> Enable testing and linting in CI workflow

.github/workflows/ci.yaml, .github/workflows/publish.yaml, Cargo.lock, Cargo.toml, src/base_client.rs, src/gevulot_client.rs, src/gov_client.rs, src/lib.rs, src/models/metadata.rs, src/models/mod.rs, src/models/pin.rs, src/models/serialization_helpers.rs, src/models/task.rs, src/models/worker.rs, src/models/workflow.rs, src/runtime_config.rs, src/signer.rs
Testing & linting is now enabled on this repo.
- Hex-encoded private key support (#47)
- Custom chain ID and token denomination for Gevulot client (#53)
- Conversion from Base client to Gevulot client (#55)
- Byte/Core/Time units now exposed as `u64` instead of `i64` (#51)
- Default factors now respect SI units: kibi/mebi/gibi-bytes added, kilo/mega/giga-bytes switched to power of 10 (#57)
- Byte/Core/Time units exposed to public API (#51)
- `signer` module exposed to public API (#56)
=> Release 0.3.0

Cargo.lock, Cargo.toml, src/base_client.rs
It is a "major update" because the interface of `gevulot_rs::base_client::BaseClient` has changed.
Tagging `v0.4.0` after merging this.
=> Release version 0.4.0

proto/gevulot/gevulot/task.proto, src/models/serialization_helpers.rs, src/models/task.rs, src/models/worker.rs
Using `CoreUnit::from(n: u64)` in that cases is not correct: proto values are in millicores and `CoreUnit::from()` converts directly into `CoreUnit::Number(n)`, which represents full cores.
Fixes #64
=> Fix conversion of proto values into CoreUnit-s (for CPU and GPU)
